# Cloud Build pipeline to provision infra (Terraform), package & deploy Cloud Function,
# and optionally deploy frontend to Firebase Hosting.
#

logsBucket: "gs://$PROJECT_ID-cloudbuild-logs"

steps:
# 1) Retrieve function-env-vars from Secret Manager
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: 'Download function-env-vars'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret="function-env-vars" > backend/function-env-vars.yaml']

# 2) Deploy Cloud Functions
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: 'Deploy Cloud Functions'
  dir: 'backend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy my-family-album-api \
        --region $_REGION \
        --project $PROJECT_ID \
        --gen2 \
        --allow-unauthenticated \
        --entry-point main \
        --runtime python311 \
        --trigger-http \
        --source=. \
        --memory=256MB \
        --service-account=$_SERVICE_ACCOUNT \
        --run-service-account=$_SERVICE_ACCOUNT \
        --env-vars-file function-env-vars.yaml

# 3) Deploy frontend to Firebase Hosting
- name: node:20
  id: 'Install Firebase CLI'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      npm install -g firebase-tools
      firebase deploy --only hosting --project $PROJECT_ID
