# Cloud Build pipeline to provision infra (Terraform), package & deploy Cloud Function,
# and optionally deploy frontend to Firebase Hosting.
#

logsBucket: "gs://$PROJECT_ID-cloudbuild-logs"

steps:
# 1) Deploy Cloud Functions
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: 'Deploy Cloud Functions'
  dir: 'backend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy my-family-album-api \
        --project $PROJECT_ID \
        --no-allow-unauthenticated \
        --entry-point main \
        --gen2 \
        --runtime python311 \
        --trigger-http \
        --source=. \
        --memory=256MB \
        --service-account=$_SERVICE_ACCOUNT \
        --set-env-vars "IMAGES_BUCKET=$_IMAGES_BUCKET,\
                        FIREBASE_ADMIN_SECRET_NAME=$_FIREBASE_ADMIN_SECRET_NAME,\
                        FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID,\
                        ALLOWED_ORIGINS=$_ALLOWED_ORIGINS,\
                        FIREBASE_API_KEY=$_FIREBASE_API_KEY,\
                        FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN,\
                        FIREBASE_APP_ID=$_FIREBASE_APP_ID,\
                        API_BASE_URL=$_API_BASE_URL"

# 2) Deploy frontend to Firebase Hosting
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  id: 'Firebase Deploy Hosting'
  dir: 'frontend'
  entrypoint: 'bash'
  args: ['-c', 'firebase deploy --only hosting --project $PROJECT_ID']
